{
 "title": "simple-auth",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "provider",
    "query": {
     "query": "label_values(traefik_simple_auth_http_requests_total,provider)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_simple_auth_http_requests_total{path=\"/\",provider=~\"^$provider$\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "requests by target",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host) (increase(traefik_simple_auth_http_requests_total{path=\"/\",provider=~\"^$provider$\"}[$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "request rate by user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (user) (rate(traefik_simple_auth_http_requests_total{path=\"/\",provider=~\"^$provider$\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "requests by user",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (user) (increase(traefik_simple_auth_http_requests_total{path=\"/\",provider=~\"^$provider$\", user!=\"\"}[$__range]))",
     "legendFormat": "{{user}}"
    },
    {
     "expr": "sum by (user) (increase(traefik_simple_auth_http_requests_total{path=\"/\",provider=~\"^$provider$\", user=\"\"}[$__range]))",
     "legendFormat": "unauthenticated"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, provider) (rate(traefik_simple_auth_http_request_duration_seconds_bucket{path=\"/\",provider=~\"^$provider$\"}[$__rate_interval])))",
     "legendFormat": "avg - {{provider}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, provider) (rate(traefik_simple_auth_http_request_duration_seconds_bucket{path=\"/\",provider=~\"^$provider$\"}[$__rate_interval])))",
     "legendFormat": "90% - {{provider}}"
    }
   ]
  },
  {
   "title": "redirected user agents",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(request_user_agent) (rate({app=\"traefik-simple-auth\"} |= `` | json | msg = `redirecting: no valid session found` [$__auto]))",
     "legendFormat": "{{request_user_agent}}"
    }
   ]
  },
  {
   "title": "logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (provider, code) (increase(traefik_simple_auth_http_requests_total{path=\"/_oauth\",provider=~\"^$provider$\"}[$__rate_interval]))",
     "legendFormat": "{{provider}} - {{code}}"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (provider) (traefik_simple_auth_http_request_duration_seconds_sum{path=\"/_oauth\",provider=~\"^$provider$\"} / traefik_simple_auth_http_request_duration_seconds_count{path=\"/_oauth\",provider=~\"^$provider$\"})",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=~\"traefik-simple-auth.*\"} |= `` | json | provider =~ `$provider`"
    }
   ]
  }
 ]
}