name: Test
on:
  push:
    branches-ignore:
      - main
      - logo
permissions:
  contents: read
jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
