name: Test

on:
  push:
    branches-ignore:
      - main
      - sessions

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
