name: Test

on:
  push:
    branches-ignore:
      - main
      - health

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go1.23
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
