name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go1.23
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go1.23
    with:
      image: ghcr.io/clambin/traefik-simple-auth
      dockerfile: build/Dockerfile
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@go1.23

